version: '2.1'

services:
  node-worker:
    image: node-worker
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 dist/index